name: C/C++ Debug macos

on:
  push:
    branches:
      - debug_macos

jobs:
  build_dep:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: New cmake
      run: cmake --version
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: "3.31.x"
    - name: Use cmake
      run: cmake --version
    - name: Install Autoconf
      run: |
        brew update
        brew install autoconf
    - name: check autoconf version
      run: autoconf --version
    - name: update automake for mpfr
      run: |
        curl -O -L https://github.com/supermerill/SuperSlicer_deps/releases/download/automake/automake-1.16.5.tar.gz
        tar -xzf automake-1.16.5.tar.gz
        cd automake-*
        ./configure
        make
        sudo make install
        automake --version
    - name: mkdir in deps
      run: mkdir deps/build
    - name: dep cache
      id: cache-action
      uses: actions/cache@v3
      with:
        key: macos_intel_debug_2.7
        path: deps/build/destdir
    - if: steps.cache-action.outputs.cache-hit != 'true'
      name: build deps if new cache
      run: ./BuildMacOS.sh -bd

  build:
    runs-on: macos-13
    needs: build_dep

    steps:
    - uses: actions/checkout@v3
    - name: New cmake
      run: cmake --version
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: "3.31.x"
    - name: Use cmake
      run: cmake --version
    - name: check autoconf version
      run: autoconf --version
    - name: update automake for mpfr
      run: |
        curl -O -L http://ftpmirror.gnu.org/automake/automake-1.16.5.tar.gz
        tar -xzf automake-1.16.5.tar.gz
        cd automake-*
        ./configure
        make
        sudo make install
        automake --version
    - name: dep cache
      id: cache-action
      uses: actions/cache@v3
      with:
        key: macos_intel_debug_2.7
        path: deps/build/destdir
    - name: build slicer
      run: ./BuildMacOS.sh -bsiv
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug_${{ github.event.repository.name }}-macOS-intel.tgz
        path: build/${{ github.event.repository.name }}-macOS-intel.tgz
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug_${{ github.event.repository.name }}-macOS-intel.dmg
        path: build/${{ github.event.repository.name }}-macOS-intel.dmg
